spring.application.name=RevPlay

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/revplayProject?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=revuser
spring.datasource.password=`1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.open-in-view=false

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=revplaysecretkeyrevplaysecretkeyrevplay
jwt.expiration=86400000

# ===============================
# FILE UPLOAD (Song Upload Ready)
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

# ===============================
# ANGULAR CORS SUPPORT
# ===============================
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/,file:songs/,file:covers/

# ===============================
# LOGGING (JWT DEBUG)
# ===============================
logging.level.org.springframework.security=DEBUG

# ===============================
# SWAGGER / OPENAPI CONFIGURATION
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# ===============================
# ERROR PAGES CONFIGURATION
# ===============================
server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=false
